[profile.default]
src = 'src'
out = 'foundry-out'
solc_version = '0.8.26'
optimizer_runs = 1_000_000
via_ir = true
ffi = true
gas_limit = "3000000000"
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./foundry-out" },
    { access = "read", path = "./script/config" },
    { access = "read", path = "./test/bin/" },
]
evm_version = 'cancun'
bytecode_hash = "none"

additional_compiler_profiles = [
  { name = "clPosm", optimizer_runs = 9000 }
]

compilation_restrictions = [
  { paths = "src/pool-cl/CLPositionManager.sol", optimizer_runs = 9000 }
]

[fuzz]
runs = 5 # change this for higher number of fuzz runs locally

[invariant]
runs = 5 # change this for higher number of invariant runs locally
depth = 5 # default is 500: https://github.com/foundry-rs/foundry/pull/7957

[profile.ci.invariant]
runs = 100            # The number of calls to make in the invariant tests

[profile.ci_main.fuzz]
runs = 1000

[profile.ci_main.invariant]
runs = 1000           # The number of calls to make in the invariant tests
