[profile.default]
src = 'src'
out = 'foundry-out'
solc_version = '0.8.26'
optimizer_runs = 100_000
via_ir = true
ffi = true
gas_limit = "3000000000"
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./foundry-out" },
    { access = "read", path = "./script/config" },
    { access = "read", path = "./test/bin/" },
]
evm_version = 'cancun'
bytecode_hash = "none"

# more info about compiler_profiles and restrictions here https://github.com/foundry-rs/foundry/pull/8668
additional_compiler_profiles = [
  { name = "clPosm", optimizer_runs = 9000 }
]

compilation_restrictions = [
  { paths = "src/pool-cl/CLPositionManager.sol", optimizer_runs = 9000 }
]

[fuzz]
runs = 1000 # change this for higher number of fuzz/invariant locally

[invariant]
depth = 15 # revert to 15 as default is 500: https://github.com/foundry-rs/foundry/pull/7957

[profile.ci.fuzz]
runs = 10000

[profile.ci.invariant]
runs = 1000            # The number of calls to make in the invariant tests
call_override = false  # Override calls
fail_on_revert = false # Fail the test if the contract reverts

[profile.ci_main.fuzz]
runs = 100000

[profile.ci_main.invariant]
runs = 10000           # The number of calls to make in the invariant tests
call_override = false  # Override calls
fail_on_revert = false # Fail the test if the contract reverts
